- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Copy sample config file
  command: mv /var/www/{{ http_host }}/wordpress/wp-config-sample.php /var/www/{{ http_host }}/wordpress/wp-config.php creates=/var/www/{{ http_host }}/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
     path: "/var/www/{{ http_host }}/wordpress/wp-config.php"
     regexp: "{{item.regexp}}"
     line: "{{item.line}}"
  with_items:
        - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
        - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}

- name: Restart Apache service
  service: name=apache2 state=restarted
  become: yes