version: '3.9'

services:
  react:
    image: frontend-image
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: presentation_tier
    restart: unless-stopped
    networks:
      - presentation-logic
    ports:
      - "9333:9333"
      
  flask:
    image: backend-image
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: logic_tier
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - presentation-logic
      - logic-data
    expose:
      - "5000"

  mongodb:
    image: mongo:5.0
    container_name: data_tier
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: vdt2022
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    networks:
      - logic-data
    expose:
      - "27017"

networks:
  logic-data:
  presentation-logic: