version: '3.0'

services:
  fluentd:
    build: .
    restart: always
    container_name: fluentd_vt
    ports:
      - 24224:24224
      - 5140:5140
      - 24224:24224/udp
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
  elasticsearch:
    image: elasticsearch:8.2.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9201:9200